services:
  redis:
    image: "redis:alpine"
  db:
    image: supabase/postgres
    ports:
      - "5432:5432"
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
    volumes:
      - db-data: /var/data/postgres
  rabbitmq:
    image: rabbitmq
#  elasticsearch:
#    image: elasticsearch
volumes:
  db-data: