on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    # envrionment: Test  # Apparently GitHub doesn't have there shit together and you can't use environments with reusable actions like checkout which are needed for all build jobs, dumb
    steps:
      - uses: actions/checkout@v4
      - name: "Install Poetry"
        run: pip install poetry && poetry config virtualenvs.create false
      - name: "Install tools"
        run: ./scripts/install/tools.sh
      - name: "Install packages"
        run: poetry install --with dev
      - name: "Unit Test"
        run: pytest
      - name: "API Tests"
        run: ./scripts/test/test-http.sh


